# Generated by Django 4.1 on 2023-03-03 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reruns.models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_celery_beat", "0016_alter_crontabschedule_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="RerunsFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("active", models.BooleanField(default=True)),
                ("source_url", models.URLField()),
                ("source_title", models.CharField(max_length=200)),
                ("contents", models.TextField()),
                ("interval", models.IntegerField()),
                ("entries_per_update", models.IntegerField()),
                (
                    "title_prefix",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "title_suffix",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "entry_title_prefix",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "entry_title_suffix",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "entry_order",
                    models.CharField(
                        choices=[("randm", "Random"), ("chron", "Chronological")],
                        default="randm",
                        max_length=5,
                    ),
                ),
                ("run_forever", models.BooleanField(default=True)),
                (
                    "start_time",
                    models.DateTimeField(
                        default=reruns.models.RerunsFeed.now_plus_offset
                    ),
                ),
                ("use_timezone", timezone_field.fields.TimeZoneField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
        ),
    ]
