# Generated by Django 4.1 on 2023-03-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rerunsfeed",
            name="interval_unit",
            field=models.CharField(
                choices=[("MINUTES", "Minutes"), ("HOURS", "Hours"), ("DAYS", "Days")],
                default="DAYS",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="entry_order",
            field=models.CharField(
                choices=[("random", "Random"), ("chron", "Chronological")],
                default="random",
                max_length=6,
            ),
        ),
    ]
