# Generated by Django 4.1 on 2023-03-09 02:46

from django.db import migrations, models
import django.utils.timezone
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rerunsfeed",
            old_name="source_title",
            new_name="title",
        ),
        migrations.AddField(
            model_name="rerunsfeed",
            name="last_task_run",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="entry_title_prefix",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="entry_title_suffix",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="title_prefix",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="title_suffix",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="use_timezone",
            field=timezone_field.fields.TimeZoneField(
                blank=True, choices_display="WITH_GMT_OFFSET"
            ),
        ),
    ]
