# Generated by Django 4.1 on 2023-03-03 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0002_rerunsfeed_interval_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rerunsfeed",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
