# Generated by Django 4.1 on 2023-03-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0002_rename_source_title_rerunsfeed_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rerunsfeed",
            old_name="last_updated",
            new_name="last_edited",
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="last_task_run",
            field=models.DateTimeField(blank=True),
        ),
    ]
