# Generated by Django 4.1 on 2023-03-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0003_rerunsfeed_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="rerunsfeed",
            name="task_run_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="interval_unit",
            field=models.CharField(
                choices=[("minutes", "Minutes"), ("hours", "Hours"), ("days", "Days")],
                default="days",
                max_length=7,
            ),
        ),
    ]
