# Generated by Django 4.1 on 2023-03-14 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0005_alter_rerunsfeed_use_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="rerunsfeed",
            name="source_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Scheduled datetime for the feed to first be updated (YYYY-MM-DD HH:MM, with HH in 24-hour time)",
            ),
        ),
    ]
