# Generated by Django 4.1 on 2023-03-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0007_rename_creation_date_rerunsfeed_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="rerunsfeed",
            name="feed_type",
            field=models.CharField(
                choices=[("rss", "RSS"), ("atom", "Atom")], default="rss", max_length=4
            ),
            preserve_default=False,
        ),
    ]
