# Generated by Django 4.1 on 2023-03-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0008_rerunsfeed_feed_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rerunsfeed",
            name="use_timezone",
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
