# Generated by Django 4.1 on 2023-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0009_remove_rerunsfeed_use_timezone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rerunsfeed",
            name="entries_per_update",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="interval",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="task_run_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
