# Generated by Django 4.1 on 2023-03-21 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0010_alter_rerunsfeed_entries_per_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rerunsfeed",
            name="entries_per_update",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Please enter a positive integer."
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="interval",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Please enter a positive integer."
                    )
                ]
            ),
        ),
    ]
