# Generated by Django 4.1 on 2023-03-23 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0011_alter_rerunsfeed_entries_per_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rerunsfeed",
            name="entries_per_update",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1,
                        message="Please enter a positive integer (not zero).",
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="interval",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1,
                        message="Please enter a positive integer (not zero).",
                    )
                ]
            ),
        ),
    ]
