# Generated by Django 4.1 on 2023-03-27 02:10

from django.db import migrations, models
import reruns.models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0012_alter_rerunsfeed_entries_per_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rerunsfeed",
            name="source_file",
            field=models.FileField(
                blank=True, null=True, upload_to=reruns.models._user_directory_path
            ),
        ),
    ]
