# Generated by Django 4.1 on 2023-03-27 18:21

from django.db import migrations
from django.core.files.base import ContentFile

def textfield_to_s3_filefield(apps, schema_editor):
    RerunsFeed = apps.get_model('reruns', 'RerunsFeed')

    for feed in RerunsFeed.objects.all():
        if feed.contents:
            contents = feed.contents
            feed.contents = ""
            feed.source_file.save(
                # `upload_to` determines the filename by the RerunsFeed's pk and owner
                name="ignored.xml",
                content=ContentFile(contents.encode("utf-8")),
                # Save the RerunsFeed model after saving the FileField
                save=True
            )

class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0013_alter_rerunsfeed_source_file"),
    ]

    operations = [
        migrations.RunPython(textfield_to_s3_filefield),
    ]
