# Generated by Django 4.1 on 2023-04-19 22:45

from django.db import migrations, models
import functools
import reruns.models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0014_custom_textfield_to_s3_filefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="rerunsfeed",
            name="condensed_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    reruns.models._user_directory_path, *(), **{"condensed": True}
                ),
            ),
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="source_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    reruns.models._user_directory_path, *(), **{"condensed": False}
                ),
            ),
        ),
    ]
