# Generated by Django 4.1 on 2023-04-20 02:42

from django.db import migrations, models
import functools
import reruns.models


class Migration(migrations.Migration):

    dependencies = [
        ("reruns", "0015_rerunsfeed_condensed_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rerunsfeed",
            name="contents",
        ),
        migrations.AlterField(
            model_name="rerunsfeed",
            name="source_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    reruns.models._user_directory_path, *(), **{"condensed": False}
                ),
                verbose_name="Feed File",
            ),
        ),
    ]
